### ISSUE TITLE
Stretch a feed to fill the screen

### ISSUE THREAD

**Issue by lazylazuli** [AndrewFromMelbourne/dmxwebcam#2]
Hey! 
Your program is everything I've been looking for the past few days. I have one question though, is there a way to re-size the video feed? 
I have a USB microscope plugged into my Raspberry pi, and my pi is connected to a 4" HDMI touchscreen and the image fills only a small part in the middle. is there any way to stretch the image to fill the whole screen? 

Regards.

**Comment by AndrewFromMelbourne** [comment]
Hi @dani7213. I use the program to display from a USB microscope on a TV. To stretch the image full screen use the --fullscreen command line option

./dmxwebcam --fullscreen

or

./dmxwebcam -F

Hope that helps

**Comment by lazylazuli** [comment]
It works! Thank you very much.


Den søndag den 27. august 2017 skrev Andrew Duncan <notifications@github.com
