### ISSUE TITLE
Running the program kills ethernet connection

### ISSUE THREAD

**Issue by ahrendsen** [AndrewFromMelbourne/dmxwebcam#4]
Sorry that I can't post more details about this now, but I just wanted to mention that when I run the program my ethernet connection always seems to become disconnected. Looking through the code, it didn't seem like connection settings are ever altered. It might be because my pi doesn't have enough current supplied through the USB power cord. I'll post more information as I learn more about the issue. 

Right now, I just restart the pi when the internet connection is needed to transfer files from the pi.

https://github.com/AndrewFromMelbourne/dmxwebcam/issues/new

**Comment by ahrendsen** [comment]
It does appear to have been a power issue. I changed to a power supply with 1.2 A current and haven't experienced any issues thus far.

**Comment by AndrewFromMelbourne** [comment]
Sorry I missed your original question. I am glad you found a resolution. It certainly sounded like a power problem.
