### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by kingearwig** [AndrewFromMelbourne/dmxwebcam#8]
when I try to compile I get an error... kind of a noob at this stuff here is the error
```
pi@basestationpi:/share/dmxwebcam $ sudo make ./dmxwebcam
cc     dmxwebcam.c   -o dmxwebcam
dmxwebcam.c:53:10: fatal error: bcm_host.h: No such file or directory
 #include "bcm_host.h"
          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by AndrewFromMelbourne** [comment]
The file should be in /opt/vc/include/bcm_host.h if it isn't there try installing the libraspberrypi-dev package.

**Comment by kingearwig** [comment]
Compiled successfully after running cmake first per the readme duh sorry
